# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-13 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistmodel',
            name='taskid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
