version: '3.7'

services:
  web:
    restart: always
    build: .\myTodoListBackend
    command: python manage.py runserver 0.0.0.0:8000
    #volumes:
    #  - ./app/:/app/
    ports:
      - 8000:8000
    depends_on:
      - db
    links:
      - db
  
  frontend:
    build:
      context: .\mywebapplication
      dockerfile: Dockerfile
    command: ["npm", "start"]
    #volumes:
    #  - ./frontend:/app/frontend
    #  - node-modules:/app/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres
    container_name: db
    #volumes:
    # - ./postgres_data:/var/lib/postgresql/data/       //volumes not mounted -> docker not able to mount on my windows machine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432' 

